### ISSUE TITLE
The RequireJS config in the bootstrap WebJar may need to be updated

### ISSUE THREAD

**Issue by akkie** [webjars/bootstrap#35]
I get this error:

```
The webjars.path() method of getting a WebJar path has been deprecated.  The RequireJS config in the bootstrap WebJar may need to be updated.  Please file an issue: http://github.com/webjars/bootstrap/issues/new
```

**Comment by jamesward** [comment]
You need to use a newer version of this WebJar.

**Comment by djechelon** [comment]
Hi, I have the same problem on version [3.3.5](http://mvnrepository.com/artifact/org.webjars/bootstrap/3.3.5). That version is from June 2015 so I am puzzled about this issue.

Exact error message is

    The webjars.path() method of getting a WebJar path has been deprecated.  The RequireJS config in the bootstrap WebJar may need to be updated.  Please file an issue: http://github.com/webjars/bootstrap/issues/new


I have defined the following Ivy dependencies

		<dependency org="org.webjars" 						name="webjars-locator" 					rev="0.27"		   		transitive="false"          conf="compile->*"/>
		<dependency org="org.webjars" 						name="webjars-locator-core"				rev="0.27"		   		transitive="false"          conf="compile->*"/>
		<dependency org="org.webjars" 						name="bootstrap" 						rev="3.3.5"		   		transitive="false"          conf="compile->*"/>
		<dependency org="org.webjars" 						name="jquery" 							rev="2.1.4"		   		transitive="false"          conf="compile->*"/>
		<dependency org="org.webjars" 						name="requirejs" 						rev="2.1.20"	   		transitive="false"          conf="compile->*"/>


Thank you for your support

**Comment by jamesward** [comment]
@djechelon That is odd.  I'm not sure what would be causing this.  Think you can put together a reproducible test case for this?
