### ISSUE TITLE
ERROR "bootstrap.min.css.map" NOT FOUND in spring-boot jsf project

### ISSUE THREAD

**Issue by mtbadi39** [webjars/bootstrap#42]
We have a spring-boot project with JSF (Mojarra 2.2.12) :
With version 3.3.5 of Bootstrap webjars all is working with no error;
After upgading to version 3.3.6; an error occured with message :  
```
StatusCode : 404
ErrorMessage : Not Found
RequestUri : /javax.faces.resource/bootstrap/3.3.6/css/bootstrap.min.css.map
```
Here is my xhtml :
```xhtml
<h:outputStylesheet library="webjars" name="bootstrap/3.3.6/css/bootstrap.min-jsf.css"/>
<h:outputStylesheet library="webjars" name="bootstrap/3.3.6/css/bootstrap-theme.min-jsf.css"/>
....................
....................
<h:outputScript library="webjars"    name="bootstrap/3.3.6/js/bootstrap.min.js"/>
```

**Comment by jamesward** [comment]
I'm not sure what the problem might be because the file is in the WebJar:
http://www.webjars.org/listfiles/org.webjars/bootstrap/3.3.6

Do all of the other files load correctly?

**Comment by mtbadi39** [comment]
Hi, 
am import just these 03 files, and yes,  i can confirme that all of them was loaded and my project run correctly, ex : nav-bar work perfectly with no problem ! even this message still visible in the log.

**Comment by jamesward** [comment]
I think I'll need more details on this problem.  I don't understand if this is an issue with your container, how you are using the WebJar, or with the WebJar itself.

**Comment by mtbadi39** [comment]
Sorry for that, but i think the problem was Firefox Cache related !
when am using Chrome the error disappear, and when i return to Firefox and clean cache, the error also disappear !
i can't prove that, but i think this is the problem. 
Regards
