### ISSUE TITLE
Wrong link in documentation

### ISSUE THREAD

**Issue by hubertgrzeskowiak** [webjars/bootstrap#44]
Hi,

http://www.webjars.org/documentation#jsf states that you should use
>     bootstrap/3.1.0/css/bootstrap.min.css

whereas the right way to include it in JSF is

>     bootstrap/3.1.0/css/bootstrap.min-jsf.css

Without the special jsf version, Glyph Icons won't work.

Also PLEASE add some contact information on the website. It's very hard to learn who is behind this project.

Cheers
Hugo

**Comment by jamesward** [comment]
This will be fixed shortly.

**Comment by hubertgrzeskowiak** [comment]
Thanks
