### ISSUE TITLE
Pagination class does not work ?

### ISSUE THREAD

**Issue by id042013** [webjars/bootstrap#49]
Pagination class does not work if I import this jar in my work, nor if I extract and use the "bootstrap.min.css" in a plain HTML file, whilst all works fine using the original css files downloaded from bootstrap, as well as CDN.  Can someone else confirm ?

`<ul class="pagination"> ... </ul>`

**Comment by jamesward** [comment]
Can you confirm that you are using the exact same versions of `bootstrap`?

**Comment by id042013** [comment]
If you mean the jar version, I used "4.0.0-alpha.5".  
When I said that something worked, I meant to say the bootstrap downloaded from getbootstrap.com or from CDN. So the HTML syntax I used is fine.

**Comment by jamesward** [comment]
Is the CDN version you used also `4.0.0-alpha.5`?

**Comment by id042013** [comment]
the CDN I used is `<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">` and the same is true for the version I downloaded.

**Comment by jamesward** [comment]
That is version `3.3.7` so you need to use the same version of the WebJar.
