### ISSUE TITLE
Make use of the distribution files

### ISSUE THREAD

**Issue by morpheus-87** [webjars/bootstrap#50]
Is there any reason for not taking the distribution files into the WebJar?

**Comment by jamesward** [comment]
We use their release on GitHub:
https://github.com/webjars/bootstrap/blob/master/pom.xml#L52

Where are you seeing something that doesn't use the distribution files?  What version?

**Comment by morpheus-87** [comment]
I tried the versions `3.3.6`, `3.3.7` and `3.3.7-1`, but there is not folder `dist`.

**Comment by jamesward** [comment]
Here are the contents for `3.3.7-1`: http://www.webjars.org/listfiles/org.webjars/bootstrap/3.3.7-1

This is the contents of the `dist` dir and a few other dirs:
https://github.com/webjars/bootstrap/blob/master/pom.xml#L113-L114
