### ISSUE TITLE
Remove deprecated webjars.path

### ISSUE THREAD

**Issue by JanBessai** [webjars/bootstrap#70]
The require.js config [uses `webjars.path`](https://github.com/webjars/bootstrap/blob/c8c7d78a682936235d43d007e98fcb8628c30a6b/src/main/resources/webjars-requirejs.js#L6), which [is deprecated](https://github.com/webjars/webjars-locator/blob/7deefda582e06371d959503299ddc20c58e579e6/src/main/java/org/webjars/RequireJS.java#L149).

I could not find decent documentation on how to replace it.

**Comment by jamesward** [comment]
Can you use a newer version of this dependency?

**Comment by JanBessai** [comment]
Which one do you mean?

Is this repository (webjars/bootstrap) deprecated/outdated? Or do you mean `webjars-locator`?

**Comment by jamesward** [comment]
Oh, sorry.  I misread this.

**Comment by jamesward** [comment]
Usually the `webjars-requirejs.js` file is only used in older WebJars.  I need to investigate if / why it is being used still.  What version of `webjars-locator` are you using?

**Comment by JanBessai** [comment]
I re-checked and the generated code didn't include it anymore. I guess this is fixed, thanks!
