### ISSUE TITLE
Please Release Version: 2.0.2

### ISSUE THREAD

**Issue by khanr1** [webjars/bootstrap#85]
Could you please  please release this ? it would make it easy for people following Play for scala book to have this  version as it is the one used in the book

**Comment by jamesward** [comment]
Can you help me find the right upstream zip?  I tried:
https://getbootstrap.com/2.0.2/

But the download link is broken.  Then I tried:
http://bootstrapdocs.com/v2.0.2/docs/index.html

But the contents of the zip seem to be for the `2.0.1` release.

**Comment by khanr1** [comment]
Hi James,

I did not pay attention that the content of the zip from http://bootstrapdocs.com/v2.0.2/docs/index.html was not 2.0.2. Unfortunately I can only find the CSS version in the git of the book I am studying.

https://github.com/playforscala/sample-applications/blob/master/ch02-your-first-play-application/first-sample/public/stylesheets/bootstrap.css

But I guess that this won't do. I will look around if I can find the ZIP but in any case thank you for coming back to me.

**Comment by thocou** [comment]
The link for this version is on https://getbootstrap.com/2.0.2/ : https://github.com/twbs/bootstrap/raw/v2.0.2/docs/assets/bootstrap.zip

Though I don't know if it's still relevant :)

**Comment by khanr1** [comment]
Waow!  thank you a lot!

**Comment by jamesward** [comment]
I'm releasing `2.0.2` now.
